name: "01 - Building Blocks"
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
echo-Failed:
    runs-on: ubuntu-latest
    steps:
      - name: Fail Step
        run: echo "This step is designed to fail" 
         exit 1        
echo-Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, world!"      