name: 02 - workflow Events
on: 
    push:
    pull_request:
    schedule:
     - cron: '0 0 * * 0'  # Runs every Sunday at midnight
    workflow_dispatch:
jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{github.event_name}} event."


